### ISSUE TITLE
Write doc how to run features

### ISSUE THREAD

**Issue by Mehonoshin** [howtohireme/juniorjobs.ru#104]
Now it is not obvious, in addition a have the following in master:

```
~/p/juniorjobs.ru/cucumber_test(master ✔) cucumber
Using the default profile...
Feature: JuniorJobs sign up
  In order to use juniorjobs
  As a registered user
  I need to sign up

  Background:
    Given I am on the juniorjobs signUp page

  Scenario: Sign up with valid credentials
    Given I have credentials with all fields
    When I fill the sign up form and submit
      timed out after 30 seconds, waiting for #<Watir::TextField: located: false; {:id=>"user_email", :tag_name=>"input"}> to be located (Watir::Exception::UnknownObjectException)
      (eval):1:in `process_watir_call'
      ./features/support/pages/sign_up.rb:17:in `fill_form'
      ./features/step_definitions/sign_up.rb:9:in `/^I fill the sign up form and submit$/'
      features/sign_up.feature:11:in `When I fill the sign up form and submit'
    Then user redirect to home page
    Then user see success msg "Вы успешно зарегистрировались"

  Scenario: Sign up with blank name
    Given I have credentials without email
    When I fill the sign up form and submit
      timed out after 30 seconds, waiting for #<Watir::TextField: located: false; {:id=>"user_email", :tag_name=>"input"}> to be located (Watir::Exception::UnknownObjectException)
      (eval):1:in `process_watir_call'
      ./features/support/pages/sign_up.rb:17:in `fill_form'
      ./features/step_definitions/sign_up.rb:9:in `/^I fill the sign up form and submit$/'
      features/sign_up.feature:17:in `When I fill the sign up form and submit'
    And account should not be created and use see signup form

Failing Scenarios:
cucumber features/sign_up.feature:9
cucumber features/sign_up.feature:15

2 scenarios (2 failed)
9 steps (2 failed, 3 skipped, 4 passed)
1m2.961s
```

**Comment by ToshiDono** [comment]
https://github.com/howtohireme/juniorjobs-features/pull/2
https://github.com/howtohireme/juniorjobs.ru/pull/135
